src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: "App\Repository\ProjectRepository")]
class Project
{
    #[ORM\Id, ORM\GeneratedValue, ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private string $name;

    #[ORM\Column(type: 'datetime')]
    private \DateTimeInterface $startDate;

    #[ORM\Column(type: 'float')]
    private float $price;

    #[ORM\OneToMany(targetEntity: "App\Entity\Tasks", mappedBy: "idTask", orphanRemoval: true)]
    private Collection $idProject;

    #[ORM\ManyToOne(targetEntity: "App\Entity\Client", inversedBy: "idProjectForClient")]
    #[ORM\JoinColumn(nullable: false)]
    private ?Client $IdClient = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $forfait = null;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: "IdProject")]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $IdUser = null;

    #[ORM\Column(type: 'datetime', nullable: true)]
    private ?\DateTimeInterface $endDate = null;

    public function __construct()
    {
        $this->idProject = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getStartDate(): \DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;
        return $this;
    }

    public function getPrice(): float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @return Collection<int, Tasks>
     */
    public function getIdProject(): Collection
    {
        return $this->idProject;
    }

    public function addIdProject(Tasks $idProject): self
    {
        if (!$this->idProject->contains($idProject)) {
            $this->idProject[] = $idProject;
            $idProject->setIdTask($this);
        }

        return $this;
    }

    public function removeIdProject(Tasks $idProject): self
    {
        if ($this->idProject->contains($idProject)) {
            $this->idProject->removeElement($idProject);
            if ($idProject->getIdTask() === $this) {
                $idProject->setIdTask(null);
            }
        }

        return $this;
    }

    public function getIdClient(): ?Client
    {
        return $this->IdClient;
    }

    public function setIdClient(?Client $IdClient): self
    {
        $this->IdClient = $IdClient;
        return $this;
    }

    public function getForfait(): ?int
    {
        return $this->forfait;
    }

    public function setForfait(?int $forfait): self
    {
        $this->forfait = $forfait;
        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->IdUser;
    }

    public function setIdUser(?User $IdUser): self
    {
        $this->IdUser = $IdUser;
        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;
        return $this;
    }
}

src/Entity/Tasks.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: "App\Repository\TasksRepository")]
class Tasks
{
    #[ORM\Id, ORM\GeneratedValue, ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private string $name;

    #[ORM\Column(type: 'datetime')]
    private \DateTimeInterface $taskDate;

    #[ORM\Column(type: 'integer')]
    private int $hourWorked;

    #[ORM\Column(type: 'text')]
    private string $description;

    #[ORM\ManyToOne(targetEntity: "App\Entity\Project", inversedBy: "idProject", cascade: ["persist"])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Project $idTask = null;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $totalHour = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getTaskDate(): \DateTimeInterface
    {
        return $this->taskDate;
    }

    public function setTaskDate(\DateTimeInterface $taskDate): self
    {
        $this->taskDate = $taskDate;
        return $this;
    }

    public function getHourWorked(): int
    {
        return $this->hourWorked;
    }

    public function setHourWorked(int $hourWorked): self
    {
        $this->hourWorked = $hourWorked;
        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getIdTask(): ?Project
    {
        return $this->idTask;
    }

    public function setIdTask(?Project $idTask): self
    {
        $this->idTask = $idTask;
        return $this;
    }

    public function getTotalHour(): ?int
    {
        return $this->totalHour;
    }

    public function setTotalHour(?int $totalHour): self
    {
        $this->totalHour = $totalHour;
        return $this;
    }
}

src/Form/TasksType.php
<?php

namespace App\Form;

use App\Entity\Project;
use App\Entity\Tasks;
use App\Form\ProjectType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;

class TasksType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, [
                'label'=>'Nom de la tâche'
            ])
            ->add('taskDate', DateType::class, [
                'label'=>'Dâte d\'exécution de la tâche',
                'widget' => 'single_text',
                'html5' => false,
            ])
            ->add('hourWorked', null, [
                'label'=>'Nombre d\'heures travaillées sur la tâche'
            ])
            ->add('description', TextareaType::class, [
                'label'=>'Description de la tâche'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Tasks::class,
           
        ]);
    }
}

src/Controller/TasksController.php
<?php

namespace App\Controller;

use App\Entity\Tasks;
use App\Entity\Project;
use App\Form\TasksType;
use App\Repository\ProjectRepository;
use App\Repository\TasksRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @Route("/tasks")
 */

class TasksController extends AbstractController
{
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
   
    /**
     * @Route("/{id}", name="tasks_index", methods={"GET"}, options={"expose"=true}, requirements={"id":"\d+"})
     */
    public function index(
        int $id,
        TasksRepository $repo,
        ProjectRepository $projRepo,
        Request $request
    ): Response {

        /** @var User $user */
        $user = $this->getUser();
        $idUser = $user->getId();

        // Find the Project by ID
        $project = $projRepo->find($id);

        if (!$project) {
            throw $this->createNotFoundException('No project found for id '.$id);
        }

        $projects = $projRepo->findAllByUser($idUser);
        $tasks5 = $repo->FiveFirstOrderByDate($project);
        $tasks = $repo->findAllOrderByDate($project);
        $tasks5Asc = $repo->FiveFirstOrderByDateAsc($project);
        $tasksAsc = $repo->findAllOrderByDateAsc($project);
        $hour = $repo->countTotalHour($project);

        return $this->render('tasks/index.html.twig', [
            'controller_name' => 'TasksController',
            'tasks' => $tasks,
            'tasks5' => $tasks5,
            'tasksAsc' => $tasksAsc,
            'tasks5Asc' => $tasks5Asc,
            'project' => $project,
            'user' => $user,
            "counthour" => implode(',', $hour),
            'projects' => $projects
        ]);
    }
    /**
     * gère le tableau des tâches en ajax
     * @Route("/tri/{id}", name="tasks_tri")
     * 
     * @return void
     */
    public function tri(int $id, Request $request, ProjectRepository $projectRepo, TasksRepository $repo, ProjectRepository $projRepo): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $idUser = $user->getId();
        $project = $projRepo->find($id);
        $tasks = $repo->findAllOrderByDate($project);
        $tasks5 = $repo->FiveFirstOrderByDate($project);
        $tasksAsc = $repo->findAllOrderByDateAsc($project);
        $projects = $projRepo->findAllByUser($idUser);
        $triValue = $request->request->get('triValue');
        
        if ($triValue == 'croissant') {
            $tasks;
        } else {
            $tasksAsc;
        }
        
        return $this->render('tasks/index.html.twig', [
            'controller_name' => 'TasksController',
            'tasks' => $tasks,
            'tasksAsc' => $tasksAsc,
            'project' => $project,
            'user' => $user,
        ]);
    }

    /**
     * gère le tableau des tâches en ajax
     * @Route("/ajax/{id}", name="tasks_ajax")
     * 
     * @return void
     */
    public function ajaxTask(int $id, Request $request, ProjectRepository $projectRepo, TasksRepository $repo): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $idUser = $user->getId();
        $project = $projectRepo->findOneBy(['id'=> $id]);
        $tasks = $repo->findAllOrderByDate($project);
        $tasksAsc = $repo->findAllOrderByDateAsc($project);
        $croissant = $request->request->get('croissant');
        $decroissant = $request->request->get('decroissant');
        $triValue =$request->request->get('triValue');
      // dd($triValue);
        foreach ($tasks as $task) {
            $taskAll[]= [
                'id'=> $task->getId(),
                'name'=>$task->getName(),
                'hour'=>$task->getHourWorked(),
                'date'=>$task->getTaskDate()
                ];
            
        }
        foreach ($tasksAsc as $taskAsc) {
            $taskAllAsc[] =[
                'id' => $taskAsc->getId(),
                'name' => $taskAsc->getName(),
                'hour' => $taskAsc->getHourWorked(),
                'date' => $taskAsc->getTaskDate()
                ];
            
        }

        $value = [
            'croissant' => $croissant,
            'decroissant' => $decroissant,
            'triValue' => $triValue,
            'tasks' => $taskAll,
            'tasksAsc' =>$taskAllAsc
        ];
        $response = new JsonResponse();
        $response->setData(['data' => $value]);
       $response->headers->set('Content-Type', 'application/json');

        return $response;
    }

    /**
     * @Route("/{id}/new", name="tasks_new", methods={"GET","POST"})
     */
    public function new(int $id, Request $request, ProjectRepository $repo): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $idUser = $user->getId();
        $projects = $repo->findAllByUser($idUser);
        $project = $repo->findOneBy(['id'=> $id]);
        $idProject = $project->getId();
        $task = new Tasks;
        $task->setIdTask($project);
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->entityManager->persist($task);

            $this->entityManager->flush();


            return $this->redirectToRoute('tasks_index',  ["id" => $idProject]);
        }

        return $this->render('tasks/new.html.twig', [
            'user' => $user,
            'task' => $task,
            'form' => $form->createView(),
            'projectName' => $project->getName(),
            'projects' => $projects,
            'project' => $project
        ]);
    }
    /**
     * @Route("/show/{id}", name="tasks_show", methods={"GET"})
     */
    public function show(TasksRepository $taskRepo, ProjectRepository $repo, int $id): Response
    {
       /** @var User $user */ 
        $user = $this->getUser();
        $idUser = $user->getId();
        $projects = $repo->findAllByUser($idUser);   
      
        $task = $taskRepo->findOneBy(array('id'=> $id));

        return $this->render('tasks/show.html.twig', [
            'task' => $task,
            'user' =>$user,
            'projects' => $projects,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="tasks_edit", methods={"GET","POST"})
     */
    public function edit(int $id, Request $request, TasksRepository $taskRepo, ProjectRepository $repo): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $idUser = $user->getId();
        $projects = $repo->findAllByUser($idUser);
        $project = new Project;
        $task = $taskRepo->findOneBy(array('id'=> $id));
        $form = $this->createForm(TasksType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();
            $idProject = $task->getIdTask()->getId();
            return $this->redirectToRoute('tasks_index', ["id" => $idProject]);
        }

        return $this->render('tasks/edit.html.twig', [
            'task' => $task,
            'project' => $project,
            'user' =>$user,
            'projects'=>$projects,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}/delete", name="tasks_delete", methods={"DELETE"})
     */
    public function delete(int $id, Request $request, TasksRepository $taskRepo): Response
    {
        $task = $taskRepo->findOneBy(array('id'=> $id));
        if ($this->isCsrfTokenValid('delete' . $task->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($task);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('home');
    }
}

templates/tasks/_delete_form.html.twig
<div>
<form method="post" action="{{ path('tasks_delete', {'id': task.id}) }}" onsubmit="return confirm('Etes-vous sur de vouloir supprimer cette tâche ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ task.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>
<p class="text-danger"><small><i class="fa fa-exclamation-triangle"></i> La suppression de cette tâche est définitive.</small></p>
</div>

templates/tasks/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
    <div class="form-group">
        {{ form_label(form.name, null, {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.name) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.taskDate, null, {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(form.taskDate, {'attr': {'class': 'form-control datepicker'}}) }}
            {{ form_errors(form.taskDate) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.hourWorked, null, {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(form.hourWorked, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.hourWorked) }}
        </div>
    </div>

    <div class="form-group">
        {{ form_label(form.description, null, {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
        <div class="col-sm-10">
            {{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.description) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button class="btn btn-outline-warning">{{ button_label|default('Enregistrer') }}</button>
        </div>
    </div>
{{ form_end(form) }}

templates/tasks/edit.html.twig
{% extends 'base.html.twig' %} {% block title %}Edit Tasks{% endblock %} {% block body %}
<h1 class='my-5'>Modifier mes tâches</h1>

{{ include('tasks/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
<div class="d-flex justify-content-between">

 {{ include('tasks/_delete_form.html.twig') }}
 <div>
<a class='btn btn-outline-secondary' href="{{ path('tasks_show', {'id': task.id}) }}">Retour à mes tâches</a>
</div>
 </div>
{% endblock %}

templates/tasks/index.html.twig
			{% extends 'base.html.twig' %}
			{% block title %}Mes tâches
			{% endblock %}
			{% block body %}
			<div class="card mb-5">
				<div class="d-flex justify-content-between">
					<h3 class="card-header text-warning">
						{{ project.name }}</h3>
					{% if project.endDate != null %}
					<p class="card-header bg-danger text-light">Projet clôturé le :
						{{ project.endDate | date('d-m-Y') }}</p>
					{% endif %}
					<a class="btn btn-primary text-warning" href="{{ path('project_edit', {'id': project.id}) }}">Modifier
						{% if project.endDate != null %}ou réouvrir {% else %}ou clôturer {% endif %}le projet</a>
				</div>

				<div class="card-body">
					<ul class="list-group list-group-flush">
						<li class="list-group-item">Client :
							<a href="{{ path('client_show', {'id': project.idClient.id}) }}">{{ project.IdClient.name }}</a></li>
						<li class="list-group-item">Début du projet :
							{{ project.startDate | date('d-m-Y') }}</li>
						{% if project.price > 0 %}
						<li class="list-group-item">Tarif horaire :
							{{ project.price }} €</li>
						{% else %}
						<li class="list-group-item">Tarif au forfait :
							{{ project.forfait }} €</li>
						{% endif %}

						{% if counthour %}
						<li class="list-group-item">Total des heures travaillées :
							{{ counthour }}
							{% if counthour == 1  %}
							heure
							{% else %}
							heures
							{% endif %}</li>

						{% if project.price > 0 %}
						<li class='list-group-item'>Montant total : {{ counthour * project.price }} €</li>
						{% endif %}
						{% endif %}
					</ul>
					{% if project.endDate == null %}
					<div class='d-flex justify-content-left'>
						<a class="btn btn-outline-warning" href="{{ path('facture', {'id': project.id}) }}">Simuler la facture en
							ligne</a>
						<a class="btn btn-outline-warning" href="{{ path('facture_edit', {'id': project.id}) }}"
							target="blank">Prévisualiser la facture en PDF</a>
					</div>
					{% endif %}
				</div>
			</div>

			<h3 class="mx-2 my-4">Les tâches de {{ project.name }}</h3>
			<div class='d-flex justify-content-between mb-4'>
				<button class='btn btn-outline-secondary' id='js-seeAll'>Voir toutes les tâches</button>
				<form action="" method="post">
					<select class="btn btn-outline-secondary mb-3" name="tri" id="tri">
						<option value="title" selected>Trier les tâches</option>
						<option value="decroissant" id='js-decroissant'>de la plus ancienne à la plus récente</option>
						<option value="croissant" id='js-croissant'>de la plus récente à la plus ancienne</option>
					</select>
				</form>
			</div>
			<div id='js-allTasksAll'>
				<div class='show' id='js-allTasks'>
					<table class='table my-3' id='js-tasktbody'>
						<thead>
							<tr class='table-warning'>
								<th>Nom de la tâche</th>
								<th>Date de la tâche</th>
								<th>Heures travaillées</th>
								{% if project.endDate == null %}
								<th><a class='btn btn-outline-primary' href="{{ path('tasks_new', {'id': project.id}) }}">Ajouter
										une
										nouvelle tâche</a></th>
								{% else %}
								<th></th>
								{% endif %}
							</tr>
						</thead>
						<tbody>
						<div id='js-div2' class='hidden'>
						
						</div>
							<div id='js-div' class='show'>
								{% if tasks %}
									{% for task in tasks %}
									<tr id='js-tr'>
										<td id='js-task-name'>{{ task.name }}</td>
										<td id='js-task-date'>{{ task.taskDate | date('d-m-Y') }}</td>
										<td id='js-task-hours'>{{ task.hourWorked }} {% if task.hourWorked == 1  %}
											heure
											{% else %}
											heures
											{% endif %}</td>
										<td>
											<a class='btn btn-outline-secondary' href="{{ path('tasks_show', {'id': task.id}) }}">Voir le
												détail</a>
											{% if project.endDate == null %}
											<a class='btn btn-outline-warning' href="{{ path('tasks_edit', {'id': task.id}) }}">Modifier
												la
												tâche</a>
											{% endif %}
										</td>
									</tr>
									{% endfor %}
									{% endif %}
							</div>
							
						</tbody>
					</table>
				</div>
				<div class='hidden' id='js-allTasks2'>
					<table class='table my-3' id='js-tasktbody2'>
					<thead>
						<tr class='table-warning'>
							<th>Nom de la tâche</th>
							<th>Date de la tâche</th>
							<th>Heures travaillées</th>
							{% if project.endDate == null %}
							<th><a class='btn btn-outline-primary' href="{{ path('tasks_new', {'id': project.id}) }}">Ajouter une
									nouvelle tâche</a></th>
							{% else %}
							<th></th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
						{% if tasksAsc %}	
						{% for taskAsc in tasksAsc %}
						<tr>
							<td id='js-task-name'>{{ taskAsc.name }}</td>
							<td id='js-task-date'>{{ taskAsc.taskDate | date('d-m-Y') }}</td>
							<td id='js-task-hours'>{{ taskAsc.hourWorked }} 
							{% if taskAsc.hourWorked == 1  %}
								heure
							{% else %}
								heures
							{% endif %}</td>
							<td>
								<a class='btn btn-outline-secondary' href="{{ path('tasks_show', {'id': taskAsc.id}) }}">Voir le
									détail</a>
								{% if project.endDate == null %}
								<a class='btn btn-outline-warning' href="{{ path('tasks_edit', {'id': taskAsc.id}) }}">Modifier
									la tâche</a>
								{% endif %}
							</td>
						</tr>
						{% endfor %}
						{% endif %}
					</tbody>
				</table>
				</div>
			</div>

			{% if project.endDate == null %}
			<div class='my-5'>
				<a class='btn btn-warning' href="{{ path('tasks_new', {'id': project.id}) }}">Ajouter une nouvelle tâche</a>
			</div>
			{% endif %}
			{% endblock %}
			{% block javascripts %}
			<script src="https://code.jquery.com/jquery-3.4.1.min.js"
				integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
			<script>
				$(document).ready(function () {
					var allTasks = document.querySelector("#js-allTasks");
					var allTasksAll = document.querySelector("#js-allTasksAll");
					var allTasks2 = document.querySelector("#js-allTasks2");
					var tri = document.querySelector("select");
					var tasktbody = document.getElementById("js-tasktbody");
					var taskBody = document.querySelector("#js-tasktbody");
					var taskBody2 = document.querySelector("#js-tasktbody2");
					var tr = document.querySelector('#js-tr');
					var div = document.querySelector('#js-div');
					var div2 = document.querySelector('#js-div2');

					$("#js-seeAll").click(function () {
						if (allTasksAll.classList == 'hidden2') {
							showAll();
						} else {
							removeAll();
						}
					});

					tri.addEventListener('change', function (e) {
						e.preventDefault();
						var triValue = this.value;
						var croissant = $('#js-croissant').val();
						var decroissant = $('#js-decroissant').val();

						$.ajax({
								url: '{{ path('tasks_ajax', {'id': project.id }) }}',
								method: 'POST',
								dataType: 'json',
								data: {
									croissant: croissant,
									decroissant: decroissant,
									triValue: triValue
								},

							})
							.done(function (data) {
								console.log(data.data)
								var tasks = data.data.tasks;
								var tasksAsc = data.data.tasksAsc;

								console.log(tasks);
							
								if (data.data.triValue == 'croissant')
								{ 
									showCroissant();
								//	for (t in tasks) {
										
									//	var date = dateFR(tasks[t].date.date);
									
										//console.log("NAME : "+tasks[t].hour);
										//var td = tr.append($('<td>'));
									//$('js-div2').append($('<tr>').attr('id','#js-tr'));
									//	$('#js-tr').append($('<td>').text(tasks[t].name));
									//	$('#js-tr').append($('<td>').text(date));
									//	$('#js-tr').append($('<td>').text(tasks[t].hour + 'heures'));

										//tr.append('<td>'+date+'</td>');
										//tr.append('<td>'+tasks[t].hour+'</td>');
										
									//	$('#js-task-name').innerHTML = tasks[t].name
									//	$('#js-task-date').innerHTML = date;
									//	$('#js-task-hours').text(tasks[t].hour + 'heures');
								//	}	
								} else {
									
									showDecroissant();
									//for(t in tasksAsc){
									//	var date = dateFR(tasksAsc[t].date.date);
									//	console.log("DATE : "+date);
								//	$('#js-task-name').text(tasksAsc[t].name);
								//	$('#js-task-date').text(date);
								//	$('#js-task-hours').text(tasksAsc[t].hour);
									}
									
							//	}
								
							})
							.fail(function (err) {
								alert('La requête Ajax a grave foiré !!!');
							});
					});

					function showCroissant() {
						allTasks.classList.add('show');
						allTasks2.classList.add('hidden');
						allTasks.classList.remove('hidden');
						allTasks2.classList.remove('show');
						//div2.classList.add('show');
						//div2.classList.remove('hidden');
						//div.classList.add('hidden');
						//div.classList.remove('show');
					}

					function showDecroissant() {
						allTasks.classList.add('hidden');
						allTasks2.classList.add('show');
						allTasks.classList.remove('show');
						allTasks2.classList.remove('hidden');
					}

					function showAll() {
						allTasksAll.classList.add("show2");
						allTasksAll.classList.remove("hidden2");
					}

					function removeAll() {
						allTasksAll.classList.remove("show2");
						allTasksAll.classList.add("hidden2");
					}
					function dateFR(completeDate){
						var dateEN = completeDate.substr(0, 10);
						var year = dateEN.substr(0, 4);
						var month = dateEN.substr(5, 2);
						var day = dateEN.substr(8, 2);
						var date = day + '-' + month + '-' + year;
						return date;
					}
				})
			</script>

			{% endblock %}

templates/tasks/new.html.twig
{% extends 'base.html.twig' %} {% block title %}New Tasks{% endblock %} {% block body %}
<h1 class='py-4'>Ajouter une tâche à mon projet {{ projectName }}</h1>

{{ include('tasks/_form.html.twig') }}
<div>
	<a class='btn btn-outline-secondary' href="{{ path('tasks_index', {'id': project.id}) }}">Annuler</a>
</div>
{% endblock %}